server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/${dbname}?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: 118.31.16.35
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  redis:
    host: 118.31.16.35
    port: 6379
    password: 123456

mybatis:
  type-aliases-package: com/qyl/pojo